### ISSUE TITLE
Meaning of masked items in `test_suite_cases.csv`

### ISSUE THREAD

**Issue by guanqun-yang** [paul-rottger/hate-functional-tests#1]
Thank for the great dataset! It resolves my long-standing difficulty finding quality dataset on benchmarking hate speech detectors. 

Based on my inspection on your dataset, the `test_suite_cases.csv` ​include the templates you used to generate the test cases. But it seems that the meaning of these masked items are not mentioned in your [paper](https://arxiv.org/pdf/2012.15606.pdf).

Specifically, I extracted the following masks. I know what is `SLUR` and `IDENTITY`, but I am not sure what do `S`, `A`, and `P` mean in these masked tokens?

```
[SLUR_S], [IDENTITY_S], [IDENTITY_A], 
[IDENTITY_S_char_del], [IDENTITY_P_space_add], [IDENTITY_P], 
[SLUR_S_space_add], [IDENTITY_P_leet], [IDENTITY_P_char_del], 
[SLUR_P_leet], [SLUR_P], [SLUR_S_leet], 
[SLUR_P_space_add], [IDENTITY_S_space_add]
```

**Comment by paul-rottger** [comment]
Hi!

Thanks for taking an interest in our work. Good catch! I have added a csv with the masked token values. S means “singular”, P “plural” and “A” adjective.
https://github.com/paul-rottger/hatecheck-data/blob/main/template_placeholders.csv <https://github.com/paul-rottger/hatecheck-data/blob/main/template_placeholders.csv>

Cheers,
Paul

**Comment by peluz** [comment]
Hello!

Thank you for publishing the test suite, really nice work.

There's one thing I could not find out myself:

Why do some cases (case_ids 833 to 837 of the test_suit_cases CSV, for example) have the focus word assigned as [SLUR] instead of [SLUR-S]? Conversely, case_id 2660 has a focus word of [SLUR-S], but the test case has a pluralised slur. Am I missing something?

Once again, thank you for the benchmark!

Best,
Pedro

**Comment by paul-rottger** [comment]
Hi Pedro,

Thanks for using HateCheck and for looking at it so carefully. You have indeed found a small inconsistency around how slurs are recorded in the 'focus word' column. I was wrongly using the generic [SLUR] rather than the singular or plural for the cases testing for slur usage. I have now corrected this in test_suite_cases.csv.

Additionally, you are right that the focus word for case_ids 2560 (I think your 2660 was a typo) to 2577 should be [SLUR_P] rather than [SLUR_S]. I have also fixed this.

Hope that helps!

All the best,
Paul

PS, in the future, please open a separate issue rather than commenting on an existing but (mostly) unrelated one. I will close this issue now 🤗

**Comment by peluz** [comment]
Thank you very much, Paul, I think I understand now. 

Sorry about commenting on this unrelated issue, I'll keep that in mind in the future :)
